### ISSUE TITLE
For recurrent models, are positional embeddings required?

### ISSUE THREAD

**Issue by rongcuid** [idiap/fast-transformers#102]
Great papers and thank you for the library. I have successfully reproduced the _Transformers are RNN_ paper from scratch. However, I have some questions about the use of positional encoding.

1. For the Causal Linear attention, I see that it is implemented as a recurrent model. Does this imply that positional embedding is not required, like "normal" RNN models?
2. For the non-causal attention (such as when used as an encoder that sees the entire sequence), I am using Rotary Positional Embedding. Do you have any comments? Would it be better to use causal attention on the encoder as well?

Thank you for your great work.

**Comment by rongcuid** [comment]
I tried my model without RoPE, and the model start predicting nonsense at many timestamps. Positional embedding definitely helps, but I don't know if it is required, or I simply did not train long enough.

**Comment by angeloskath** [comment]
Hi,

Thanks for the good words about the library.

Positional encoding is still required even though the network can be implemented as an RNN. The state updates are *permutation invariant* which means that the order is lost after each prediction.

I will close the issue but if you need more information feel free to reopen it.

Cheers,
Angelos

**Comment by rongcuid** [comment]
Thank you. My experiments also show that the model cannot learn sequence generation when positional encoding is not used.

**Comment by rongcuid** [comment]
Just noting. I did some survey, and find https://arxiv.org/pdf/1905.04226.pdf which claims autoregressive transformers do not require positional encoding. I do not have the computational capacity to try such deep models, but I suppose one can leave them out if the network is deep enough. 

In my particular model, training without positional gives bad results, but mine is only 4H/4L with 128 hiddens and 1024 FF. It might simply be a case which the model is too small.

**Comment by rongcuid** [comment]
For future reference, I can confirm that positional encoding on causal model is _not_ required. However, it requires a lot more tuning, especially in my case where multi-task learning is involved. With positional encoding applied to decoder, the model converges much faster and with more stability.
