### ISSUE TITLE
Training Language Model

### ISSUE THREAD

**Issue by lucasnfe** [idiap/fast-transformers#107]
Hi,

Thanks for such a clean implementation and documentation!

I've been trying to train a language model (to generate text) with a linear attention transformer, but I'm having problems to batchfy my dataset. I've followed this [colab](https://colab.research.google.com/drive/1BV4OaWRAHYGeimO0cqHD86GfnfgUaKD4?usp=sharing#scrollTo=ib8YRy5Zm1Pv) to build the model. I can build the model and pass a placeholder input to it successfully. However, I'm not sure how to pack textual data into batches in order to train the language model on the GPU. 

I've followed [this tutorial](https://pytorch.org/tutorials/beginner/transformer_tutorial.html) to load and batchy the data. Could you please provide an example of how to train a linear attention transformer? Perhaps the code to train that handwritten digit generator from the [colab](https://colab.research.google.com/drive/1BV4OaWRAHYGeimO0cqHD86GfnfgUaKD4?usp=sharing#scrollTo=ib8YRy5Zm1Pv)?

Thanks again!

**Comment by lucasnfe** [comment]
I just found the github repo of the image generator:
https://github.com/idiap/linear-transformer-experiments/tree/master/image-generation

**Comment by Bachstelze** [comment]
How did you train the language model in the end?
