### ISSUE TITLE
TO DO in Causal Linear denomenator

### ISSUE THREAD

**Issue by eelxpeng** [idiap/fast-transformers#11]
You mentioned in the causal linear attention that `Shall we divide the Q and K with a relatively large number to avoid numerical instabilities in computing the denominator?` Could you explain briefly why there is an instability problem? And do you have a good solution for this?
https://github.com/idiap/fast-transformers/blob/1eda2fe8363ab13b5ce00022cb869e7ef2c7298e/fast_transformers/attention/causal_linear_attention.py#L62

**Comment by angeloskath** [comment]
Hi, we have not observed this instability in practice and the workaround that we used before was an overkill but I left the comment just in case.

The instability I am talking about is the following (excuse the relatively unreadable pseudocode):

```
Q = ...
K = ...
QK = Q K^T  # arbitrarily large but probably no overflow
A = QK / QK.sum(-1)  # now we sum a possibly large number of arbitrarily large numbers possible overflow

A = (QK / 100) / (QK / 100).sum(-1) # less chances of overflow

# And the following has no chances of overflow because it ensures that all numbers in QK are less than 1
M = max(Q.norm(), K.norm())
Q /= M
K /= M
QK = Q K^T
A = QK / QK.sum(-1)
```

I hope it is clearer. If not feel free to reopen the bug report.

Cheers,
Angelos
