### ISSUE TITLE
Casual attention is cheating by looking in the future

### ISSUE THREAD

**Issue by jogardi** [idiap/fast-transformers#111]
On line 95 of casual_linear_attention.py there is a normalizing constant computed by looking at all queries and keys. This creates a dependency on future values which would be unknown in a real prediction task.

**Comment by angeloskath** [comment]
Hi,

This is not the case. Since we compute the normalizing constant using the cumsum of K, we are actually using information up to the current time step and **not from the future.**

Best,
Angelos
