### ISSUE TITLE
`.causal_product_cuda` missing in pip installed version on linux

### ISSUE THREAD

**Issue by Jackl-o-o-l** [idiap/fast-transformers#125]
I installed the package with `pip install --user pytorch-fast-transformers` using python 3.8 in linux.

`causal_product/__init__.py` fails to find `.causal_product_cuda` in line **13**
`from .causal_product_cuda import ...`

because `causal_product_cpu.cpython-38-x86_64-linux-gnu.so` is the only file left in the folder.

The file for `.causal_product_cuda` to be imported is missing.

**Comment by Jackl-o-o-l** [comment]
I tried to download the code and build it with `pip install -e .` Only `causal_product_cpu.cpp` gets compiled and `causal_product_cpu.cpython-38-x86_64-linux-gnu.so` is generated.

**Comment by Jackl-o-o-l** [comment]
The problem is finally solved with similar solution in #12

**Comment by Jackl-o-o-l** [comment]
Final update: This issue is solved after adding CUDA to PATH. 

After that `pip uninstall pytorch-fast-transformers`
and `pip install --no-cache-dir pytorch-fast-transformers`
should work.

You will find `causal_product_cuda.cpython-38-x86_64-linux-gnu.so` under folder `causal_product`

**Comment by cjmcgill** [comment]
@Jackl-o-o-l thanks for posting this fix!
