### ISSUE TITLE
Full Attention does not sum to 1

### ISSUE THREAD

**Issue by yourj4m** [idiap/fast-transformers#131]
When creating a transformer with 
```python
encoder = TransformerEncoderBuilder.from_kwargs(
            n_layers=num_layers,
            n_heads=num_heads,
            query_dimensions=d_model,
            value_dimensions=d_model,
            feed_forward_dimensions=ff_dim,
            attention_type='full',
            activation='gelu',
        ).get()
```
and doing the forward pass with
```python
encoder(data, data_mask)
```
and capturing the attention matrix as described in #20, the resulting attention matrix does not sum to 1. 
Am I missing something? Since the attention layer includes softmax, it should sum to 1, I think...

**Comment by yourj4m** [comment]
Okay nevermind, of course it sums to 1, I didn't `encoder.eval()` before testing and the dropout layer in the attention caused it to be off..
However, there is one thing I still don't understand, namely that I get values larger than one when summing without setting the model to evaluation mode. If the dropout is applied before the softmax, that shouldn't be possible and neither when it is applied after the softmax.. If anybody has an idea I'd love to hear it.

**Comment by yiyousong** [comment]
thats becuase most attention implementation does dropout after softmax. In this case, the 'norm' part of dropout tries to change the **expection** back to 1, not the **actual value**. For example, for this [0.1,0.9] input, and one values is droped, dropout will give either [0.2,0] or [0,1.8] not [1,0]
