### ISSUE TITLE
Image generation/completion

### ISSUE THREAD

**Issue by lorinczszabolcs** [idiap/fast-transformers#14]
Hello,

I can't seem to find the code corresponding to image generation/completion part of the paper. My question would be if you treat images as flattened rgb values, and wether image completion works by having N pixel values and predicting the N+1th pixel value and repeating this step until the whole image is completed.

Thank you in advance!

**Comment by angeloskath** [comment]
Hello,

Yes indeed we are predicting the next byte in an image given the previous ones. This is equal to pixels in a grayscale image and 3 times the pixels in a colored image. We are also using mixtures of logistics to model the distribution of the output.

We will release the training code in the coming weeks, however, in our [linear transformers project page](https://linear-transformers.com/) you can also find a colab where you can see the network and the inference and experiment with them.

Cheers,
Angelos

**Comment by lorinczszabolcs** [comment]
Thank you for your quick reply and explanation! Looking forward to the training code also!

All the best,
Szabi
