### ISSUE TITLE
Please Add Pytorch to Be Automatically Installed

### ISSUE THREAD

**Issue by theactiveone** [idiap/fast-transformers#15]
Hi, 
I ran into to problem that you need to manually install pytorch before running `pip install --user pytorch-fast-transformers`. It would be very convenient if `pytorch` were installed  automatically in the `setup.py`

**Comment by angeloskath** [comment]
Do you have a suggestion for how we should go about doing this?

Personally, I feel that choosing a PyTorch installation is a significant choice that this library should not be making.

Cheers,
Angelos

**Comment by angeloskath** [comment]
I will close this issue since it is stale and I still think it is not this library's place to install PyTorch.
