### ISSUE TITLE
Positional embedding

### ISSUE THREAD

**Issue by horiacristescu** [idiap/fast-transformers#17]
Hello, 
First of all,  great project and paper!

I tried but couldn't find out how positional embedding is being handled. Maybe it's a silly question, but should it be provided externally or is it implicit?

What I would like to do is to have a relative embedding not on the time axis, but on X and Y for each token as they are spatially related in a 2-D plane. These tokens could  be pixels in an image or words in a semi-structured document such as a table or a form, where important information is contained in the vertical and horizontal alignments.

I am also thinking the problem could be approached with a boolean mask that only allows vertically or horizontally aligned tokens to see each other.

Thank you

**Comment by anthonyfuller7** [comment]
This may interest you:

https://github.com/idiap/fast-transformers/issues/5#issuecomment-654876848

**Comment by angeloskath** [comment]
Hi Horia,

Thanks for the good words and sorry for the extremely late reply. The positional embedding is not something that is provided by this library. You can roll your own as you see fit. I will close the issue but feel free to reopen it if you have more questions.

Cheers,
Angelos
