### ISSUE TITLE
Cant install on colab

### ISSUE THREAD

**Issue by hadaev8** [idiap/fast-transformers#18]
Here is notebook
https://colab.research.google.com/drive/1mlkd7D1s9qs9aryXu7X1ArMevRTGYXfR?usp=sharing

**Comment by anthonyfuller7** [comment]
Colab now uses pytorch v1.6. You can downgrade to 1.5.1 via:

```
!pip uninstall torch
!pip install torch==1.5.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by angeloskath** [comment]
Thanks Anthony for the reply (I know it's been two weeks)!

A new release that permanently fixes this will be done before the end of the week.

**Comment by angeloskath** [comment]
I pushed a fix but I did not yet prepare the release. Probably later today or tomorrow because it will also contain the transformer decoders and the refactored attention builders.
