### ISSUE TITLE
hash_cuda.cu: No such file or directory

### ISSUE THREAD

**Issue by pathway** [idiap/fast-transformers#2]
```
pip install --user pytorch-fast-transformers
....

gcc: error: fast_transformers/hashing/hash_cuda.cu: No such file or directory
```
ubuntu 18.04
Python 3.6.7
CUDA Version: 10.1

**Comment by angeloskath** [comment]
Hi, thanks for the issue, I was in the process of fixing it. Basically, all cuda files were missing from the archive uploaded to PyPI.

Could you please `pip install --upgrade pytorch-fast-transformers` ? If it works I'll go ahead and close the issue.

**Comment by angeloskath** [comment]
Since it will probably be cached, you could also try `pip install pytorch-fast-transformers==0.1.3`.

**Comment by angeloskath** [comment]
I am closing the issue because it is fixed with version 0.1.3 uploaded to PyPI. Basically there was no problem with the code, just the upload.

**Comment by AceCoooool** [comment]
There is not compute_hashes_cuda in v0.3.0 (but have others like causal_dot_product_cuda)

**Comment by angeloskath** [comment]
Hi,

In our tests it seems that it compiles fine. What is the error that you are experiencing?

Check for instance https://github.com/idiap/fast-transformers/runs/1255607201?check_suite_focus=true .

Angelos
