### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Uglj** [idiap/fast-transformers#4]
Thanks for this great project!

Could you please share training code for models in colab?

Thanks!

**Comment by angeloskath** [comment]
Hi,

We will release a separate repo with our experiments for the fast autoregressive transformers paper.

However, we shall also add some training examples in this repository.

Angelos

**Comment by nile649** [comment]
Out of curiosity in the paper, the test cases are for image generation, and speech recognition, but there is no mention of any NLP task and benchmarking on them. It would be an easier comparison between your model and Bert if you could give an example on any NLP task even as simple as sentiment classification.

**Comment by angeloskath** [comment]
The training code has been released at https://github.com/idiap/linear-transformer-experiments.

Sorry for the delays.
