### ISSUE TITLE
Image Generation/Completion Training-Code

### ISSUE THREAD

**Issue by tibuch** [idiap/fast-transformers#52]
Hi,

I am looking for the training code of the image-completion/generation examples. I found the code to run your pre-trained model and it works nicely, but now I would like to understand the training process and was wondering where I could find this code.

Thank you for your help.

**Comment by robclouth** [comment]
I would very much like the same.

**Comment by angeloskath** [comment]
Hi,

You can access the training code at https://github.com/idiap/linear-transformer-experiments .

I am closing the issue but feel free to reopen it here or in the other repository if you have more questions.

Cheers,
Angelos

**Comment by robclouth** [comment]
Thanks!
