### ISSUE TITLE
Could this be used for faster-training of transformer-based object detection?

### ISSUE THREAD

**Issue by nicolasugrinovic** [idiap/fast-transformers#66]
Hi, 
Thank for the code.
A very popular implementation of transformers for computer vision is DETR which uses a vanilla transformer. However, training is slow and painful. Could this linear transformer be used for a object detector similar to DETR and expect the same computational gains?

**Comment by angeloskath** [comment]
The depends on whether the bottleneck of DETR lies in the transformer model and whether it is one that can be mitigated by a linear transformer. Namely, is the sequence too long? Is the autoregressive decoder causing the bottleneck?

If you use the library to implement DETR, then you can easily change between softmax attention and linear attention with a single one-line change.

Cheers,
Angelos

**Comment by angeloskath** [comment]
Closing the issue due to inactivity. Feel free to reopen if needed.
