### ISSUE TITLE
RecurrentCrossFullAttention have no event dispatcher for attention weight

### ISSUE THREAD

**Issue by hadaev8** [idiap/fast-transformers#71]
Would be useful for debugging.

**Comment by angeloskath** [comment]
Very good point. I will add it. In the meantime feel free to add it yourself (maybe even make a PR).

Cheers,
Angelos

**Comment by hadaev8** [comment]
Sure, i will make pr.

**Comment by angeloskath** [comment]
Just merged the pr (#72).
