### ISSUE TITLE
Some errors when I run the Quick-start code

### ISSUE THREAD

**Issue by yyysjz1997** [idiap/fast-transformers#75]
there is the error: ModuleNotFoundError: No module named 'fast_transformers.causal_product.causal_product_cpu' .

And I find this file"causal_product_cpu.cpp", which is a c++ file. Is it shown that I have not installed the c++ toolchain, I also want to know what package should I use for that.

**Comment by angeloskath** [comment]
Hi,

Did the installation complete successfully? Did you install with `pip` or from the repository?

I have the feeling that the installation did not complete successfully and you are running your code from inside the repository or having the repository in your PYTHONPATH.

Cheers,
Angelos

**Comment by angeloskath** [comment]
Hi closing the issue due to inactivity. Feel free to reopen it if you are still experiencing problems.
