### ISSUE TITLE
TransformerDecoderBuilder: decoder only self attention example

### ISSUE THREAD

**Issue by patdflynn** [idiap/fast-transformers#81]
I've reviewed the docs and I'm still a bit unclear how to build a decoder-only self attention transformer. Would you mind providing an example?

**Comment by angeloskath** [comment]
Hi,

By decoder only, do you mean an autoregressive encoder? Like for instance for image generation or text generation?

In that case any [TransformerEncoder](https://fast-transformers.github.io/builders/) used with [TriangularCausalMask](https://fast-transformers.github.io/masking/#triangularcausalmask) would do.

Cheers,
Angelos

**Comment by patdflynn** [comment]
For this project I'm comparing different models for time series forecasting but that's good to know. I figured a encoder with a linear layer at the end may be sufficient.

**Comment by angeloskath** [comment]
Thanks for your very good words! I am closing the issue as I assume that it is solved.

Feel free to reopen it or open another one in case you encounter problems.

Best,
Angelos

**Comment by KeyboardRamin** [comment]
Hi

**Comment by KeyboardRamin** [comment]
Hi
