### ISSUE TITLE
ModuleNotFoundError: No module named 'aggregate.aggregate_cpu'

### ISSUE THREAD

**Issue by TianhaoFu** [idiap/fast-transformers#93]
Hi, when i want to use clusted attention, I came across a bug. It seems because the `aggregate_cpu.cu` is a cuda type file. 

BTW， I insert the source code in code and i came across such bug.

Can you give me some advices on this bug? 

Thanks:)

**Comment by angeloskath** [comment]
Hi, did you compile the library first? You can do this by running `python setup.py build_ext --inplace`. If you installed via pip then it should have automatically compiled the library first.

Cheers,
Angelos

**Comment by TianhaoFu** [comment]
> Hi, did you compile the library first? You can do this by running `python setup.py build_ext --inplace`. If you installed via pip then it should have automatically compiled the library first.
> 
> Cheers,
> Angelos

thanks. Its work
