### ISSUE TITLE
support of cluster attention 

### ISSUE THREAD

**Issue by TianhaoFu** [idiap/fast-transformers#95]
Hi,  very good repository.

I wonder know when would the package can support transformer using cluster attention?

Thanks!

**Comment by apoorv2904** [comment]
Hi,

Clustered Attention is supported by the package. Please take a look here for the [available attention types](https://fast-transformers.github.io/attention/)

You could also take a look at [colab notebook](https://colab.research.google.com/drive/1E8BYQf3Puxb643LOyIjT-0m3yXGO28ev?usp=sharing#scrollTo=sJjXAWw83tnl) with examples of using clustered attention and some practical tips.

Hope this helps!
